import { FormEvent, useEffect, useMemo, useState } from 'react';
import { createPublicClient, fallback, getAddress, http, isAddress } from 'viem';
import { mainnet } from 'viem/chains';
import { BlockscoutClient } from './blockscout';
import { DEV_BOARD, RPCS } from './config';
import { buildThreads, openThread, type Thread } from './threads';
import './styles.css';
import './review.css';

const publicClient=createPublicClient({chain:mainnet,transport:fallback(RPCS.map(url=>http(url)))});
type Route={kind:'inbox';owner:string}|{kind:'thread';owner:string;party:string}|{kind:'notfound'};
function route():Route { const p=location.hash.replace(/^#\/?/,'').split('/').filter(Boolean);if(!p.length)return{kind:'inbox',owner:DEV_BOARD};if(p[0]==='a'&&p.length===2&&isAddress(p[1]))return{kind:'inbox',owner:getAddress(p[1])};if(p[0]==='a'&&p.length===3&&isAddress(p[1])&&isAddress(p[2]))return{kind:'thread',owner:getAddress(p[1]),party:getAddress(p[2])};return{kind:'notfound'};}
const when=(d:Date)=>new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(d);

export default function App(){
 const [current,setCurrent]=useState(route);useEffect(()=>{const h=()=>setCurrent(route());addEventListener('hashchange',h);return()=>removeEventListener('hashchange',h)},[]);
 return <div className="shell"><a className="skip" href="#main">Skip to content</a><header><a className="brand" href="#/">IDM Inbox</a><span className="network">Ethereum mainnet</span></header><main id="main">{current.kind==='notfound'?<section className="empty"><h1>Not found</h1><a href="#/">Go home</a></section>:<Inbox route={current}/>}</main><Footer/></div>;
}
function Search(){const [value,setValue]=useState('');const [error,setError]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();setError('');let address:string|null=null;if(isAddress(value))address=getAddress(value);else if(value.toLowerCase().endsWith('.eth')){try{address=await publicClient.getEnsAddress({name:value.toLowerCase()})}catch{/* shown below */}}if(address)location.hash=`/a/${address}`;else setError('Enter a valid Ethereum address or ENS name.');};return <form className="search" onSubmit={submit}><label htmlFor="address">Open an address or ENS name</label><div><input id="address" name="address" value={value} onChange={e=>setValue(e.target.value)} placeholder="Example: vitalik.eth or 0x…" autoComplete="off" spellCheck={false}/><button>Open inbox</button></div>{error&&<p className="error" role="alert">{error}</p>}</form>}
function Inbox({route:r}:{route:Extract<Route,{kind:'inbox'|'thread'}>}){const [client]=useState(()=>new BlockscoutClient(r.owner));const [,render]=useState(0);useEffect(()=>{void client.loadInitial().finally(()=>render(x=>x+1))},[client]);const threads=useMemo(()=>buildThreads(r.owner,client.state.transactions),[r.owner,client.state.transactions]);const selected=r.kind==='thread'?threads.find(t=>t.counterparty.toLowerCase()===r.party.toLowerCase()):undefined;useEffect(()=>{if(selected){openThread(r.owner,selected.counterparty);}},[r.owner,selected]);if(r.kind==='thread'&&!selected&&!client.state.loading)return <section className="empty"><h1>Thread not found</h1><a href={`#/a/${r.owner}`}>Back to inbox</a></section>;return <><section className="hero"><div><p className="eyebrow">PUBLIC ONCHAIN MESSAGES</p><h1>{r.owner.toLowerCase()===DEV_BOARD.toLowerCase()?'IMD dev board - read via IDM Inbox (independent)':'Inbox'}</h1><p className="address" title={r.owner}>{r.owner}</p></div><button className="secondary" onClick={()=>void client.refresh().finally(()=>render(x=>x+1))} disabled={client.state.loading}>Refresh</button></section>{r.owner.toLowerCase()===DEV_BOARD.toLowerCase()&&<Search/>}<div aria-live="polite" className="status">{client.state.loading?'Loading messages…':`${threads.length} thread${threads.length===1?'':'s'} loaded`}{client.state.usingFallback?' · using fallback indexer':''}</div>{client.state.error&&<div className="notice" role="alert"><span>{client.state.error}. Cached messages remain available.</span><button onClick={()=>void client.retry().finally(()=>render(x=>x+1))}>Retry</button></div>}{selected?<ThreadView owner={r.owner} thread={selected}/>:<ThreadList owner={r.owner} threads={threads}/>} {!selected&&client.state.transactions.length>0&&<button className="older" onClick={()=>void client.loadOlder().finally(()=>render(x=>x+1))} disabled={client.state.loading||client.state.historyLimit}>Load older</button>}</>}
function ThreadList({owner,threads}:{owner:string;threads:Thread[]}){if(!threads.length)return <section className="empty"><h2>No readable messages loaded</h2><p>Only successful transactions containing readable UTF-8 text appear here.</p></section>;return <section className="list" aria-label="Message threads">{threads.map(t=><a className="thread" href={`#/a/${owner}/${t.counterparty}`} key={t.counterparty}><span className="avatar" aria-hidden="true">{t.post?'P':t.label.slice(0,1).toUpperCase()}</span><span className="thread-body"><span className="thread-top"><strong>{t.label}</strong><time dateTime={t.newest.toISOString()}>{when(t.newest)}</time></span><span className="preview">{t.messages.at(-1)?.text}</span><span className="counts">{t.sent} sent · {t.received} received {t.request?'· Request':''}</span></span>{t.unread&&<span className="unread"><span className="sr-only">Unread</span></span>}</a>)}</section>}
function ThreadView({owner,thread}:{owner:string;thread:Thread}){return <section><div className="thread-heading"><a href={`#/a/${owner}`}>← Inbox</a><h2>{thread.label}</h2><p>{thread.sent} sent · {thread.received} received</p></div><ol className="messages">{thread.messages.map(m=><li className={m.sent?'sent':'received'} key={m.tx.hash}><div className="bubble"><p>{m.text}</p>{m.tags.length>0&&<small>{m.tags.join(' · ')}</small>}<footer><span>{m.sent?'Sent':'Received'}</span><time dateTime={m.date.toISOString()}>{when(m.date)}</time></footer></div></li>)}</ol></section>}
function Footer(){return <footer className="site-footer"><p>Lookups go to eth.blockscout.com, api.routescan.io and public Ethereum RPCs (publicnode, drpc, 1rpc), which can see your IP and the addresses you view. Nothing else is sent anywhere.</p><p>Hosted on IPFS via the IMD swarm's identitymd.eth name; IDM Inbox is independent of IdentityMD.</p></footer>}
