/* eslint-disable react-refresh/only-export-components */
import { useCallback, useEffect, useState } from 'react';
import { formatEther, stringToHex, type Address, type EIP1193Provider, type Hash } from 'viem';
import { FEE_REFRESH_MS, MAX_MESSAGE_BYTES } from './config';
import { loadPending, savePending, watchPending, type PendingTx } from './pending';
import { requireMainnet, useWallet, walletError } from './wallet';
import { fetchEthPrice } from './Tips';

const bytes=(value:string)=>new TextEncoder().encode(value).length;
function lookalike(recipient:string,known:string[]){const r=recipient.toLowerCase();return known.some(a=>{const x=a.toLowerCase();return x!==r&&x.slice(2,6)===r.slice(2,6)&&x.slice(-4)===r.slice(-4)})}
export async function quoteFee(provider:EIP1193Provider,tx:{from:Address;to:Address;data:`0x${string}`;value:`0x${string}`}){const [gas,block,priority]=await Promise.all([provider.request({method:'eth_estimateGas',params:[tx]}),provider.request({method:'eth_getBlockByNumber',params:['latest',false]}),provider.request({method:'eth_maxPriorityFeePerGas'})]);const base=BigInt((block as {baseFeePerGas:string}).baseFeePerGas);return BigInt(gas as string)*(2n*base+BigInt(priority as string))}

export function Composer({owner,counterparty,known=[]}:{owner:Address;counterparty?:Address;known?:string[]}){
 const wallet=useWallet();const canReply=counterparty&&wallet.account?.toLowerCase()===owner.toLowerCase();const recipient=(canReply?counterparty:owner) as Address;const [text,setText]=useState(''),[fee,setFee]=useState<bigint>(),[feeUsd,setFeeUsd]=useState<number>(),[feeError,setFeeError]=useState(false),[warning,setWarning]=useState<'contract'|'smart'>(),[understood,setUnderstood]=useState(false),[armed,setArmed]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<PendingTx|undefined>(()=>loadPending().at(-1));const count=bytes(text),similar=lookalike(recipient,known);
 const estimate=useCallback(async()=>{if(!wallet.provider||!wallet.account||!text||count>MAX_MESSAGE_BYTES){setFee(undefined);return}const tx={from:wallet.account,to:recipient,data:stringToHex(text),value:'0x0' as const};try{const [next,code,price]=await Promise.all([quoteFee(wallet.provider,tx),wallet.provider.request({method:'eth_getCode',params:[recipient,'latest']}),fetchEthPrice().catch(()=>undefined)]);setFee(next);setFeeUsd(price?Number(formatEther(next))*price.usd:undefined);setFeeError(false);const c=String(code).toLowerCase();setWarning(c.startsWith('0xef0100')?'smart':c!=='0x'?'contract':undefined)}catch{setFee(undefined);setFeeUsd(undefined);setFeeError(true)}},[wallet.provider,wallet.account,text,count,recipient]);
 useEffect(()=>{void estimate();const id=setInterval(()=>void estimate(),FEE_REFRESH_MS);return()=>clearInterval(id)},[estimate]);
 useEffect(()=>{if(!pending||!wallet.provider||pending.status!=='Pending')return;const current=pending;return watchPending(current,wallet.provider,next=>{setPending(next);const all=loadPending().filter(x=>x.hash!==next.hash);savePending([...all,next])})},[pending,wallet.provider]);
 const send=async()=>{if(!wallet.provider||!wallet.account)return;if(similar&&!armed){setArmed(true);return}setError('');try{await requireMainnet(wallet.provider);const hash=await wallet.provider.request({method:'eth_sendTransaction',params:[{from:wallet.account,to:recipient,value:'0x0',data:stringToHex(text)}]}) as Hash;let nonce:number|undefined;try{const tx=await wallet.provider.request({method:'eth_getTransactionByHash',params:[hash]}) as {nonce?:string}|null;if(tx?.nonce)nonce=Number(BigInt(tx.nonce))}catch{/* watcher continues without nonce */}const next:PendingTx={hash,nonce,created:Date.now(),status:'Pending',missingChecks:0};setPending(next);savePending([...loadPending().filter(x=>x.hash!==hash),next]);setText('');setArmed(false)}catch(e){setError(walletError(e))}};
 if(!wallet.account)return <section className="composer"><p>{wallet.provider?'Connect your wallet to send':'Install or unlock a browser wallet to send'}</p>{globalThis.matchMedia?.('(pointer: coarse)').matches&&<p>Open this page in your wallet app's browser <button className="secondary" onClick={()=>void navigator.clipboard.writeText(location.href)}>Copy link</button></p>}<button onClick={()=>void wallet.connect()} disabled={wallet.connecting}>{wallet.connecting?'Connecting…':'Connect wallet'}</button><Safety/></section>;
 const blocked=!text||count>MAX_MESSAGE_BYTES||fee===undefined||feeError||Boolean(warning&&!understood);
 return <section className="composer" aria-labelledby="compose-title"><h2 id="compose-title">{canReply?`Reply to ${counterparty}`:`Message ${owner}`}</h2><label htmlFor="message">Message</label><textarea id="message" value={text} onChange={e=>{setText(e.target.value);setArmed(false)}} rows={5}/><div className={`byte-count ${count>MAX_MESSAGE_BYTES?'error':''}`}>{count.toLocaleString()} / {MAX_MESSAGE_BYTES.toLocaleString()} bytes</div>{feeError?<p className="error">This transaction would likely fail</p>:fee!==undefined&&<p>Max fee ~ {formatEther(fee)} ETH {feeUsd!==undefined&&`($${feeUsd.toFixed(2)})`}</p>}{warning&&<label className="understand"><input type="checkbox" checked={understood} onChange={e=>setUnderstood(e.target.checked)}/><span>{warning==='smart'?'This wallet runs smart-account code; your text may run it or fail.':'This address is a contract. Your text would be sent as a function call and may do something.'} I understand</span></label>}{similar&&<p className="warning">This address looks like another one you know. Check every character.</p>}<button onClick={()=>void send()} disabled={blocked}>{similar&&!armed?'Send — review address':'Send'}</button>{error&&<p className="error" role="alert">{error}</p>}{pending&&<p className="tx-status" aria-live="polite">{pending.status}</p>}<Safety/></section>
}
function Safety(){return <p className="safety">Messages are public forever and cannot be deleted. Never share a seed phrase.</p>}
